### PR TITLE
Adding an "and" condition function to card search

### PR DESCRIPTION
**Pull request by NattyZepko**
Making the card search use the term "&&" to make an "And" function

### CODE REVIEW

**Comment by edo9300** [comment]
Thanks for the contribution, but the feature is already present https://github.com/edo9300/edopro/commit/933e0b903dfd9767b96242c2ad04d915fec18c3d, in the end what this commit changed (other than rearranging lines) is removing the handling of `a&&!!`, then, if the search is currently not working it's another matter.

**Comment by NattyZepko** [comment]
Regardless of my PR, the feature doesn't seem to work
image

**Comment by edo9300** [comment]
Are you using a version built from the master branch?

**Comment by NattyZepko** [comment]
I do.

**Comment by edo9300** [comment]
Well, you might have something wrong down the line, as the feature does work properly in the latest builds from the master branch
immagine

**Pull request closed without merging**
