### PR TITLE
Respect YGOPRO_*_PATH

### PR DESCRIPTION
**Pull request by LordYuuma**
This is a cleaner version of [guix-ygopro/edopro-respect-YGOPRO_-_PATH.patch](https://github.com/LordYuuma/guix-ygopro/blob/master/ygopro/patches/edopro-respect-YGOPRO_-_PATH.patch).  If enabled, databases and LFLists will be loaded from `YGOPRO_DATA_PATH`, scripts from `YGOPRO_SCRIPT_PATH`, and card/field/cover images from `YGOPRO_IMAGE_PATH` instead of the current working directory.  To enable, pass `--environment-paths` to premake5.

### CODE REVIEW

**Comment by LordYuuma** [comment]
2b543cab91401cde755af1a96cce582a16bdb202 and ab227f373fc8b7b2815d92168f45e692702185f6 also add some basic support for XDG variables.

**Comment by kevinlul** [comment]
To be frank, there's going to have to be a lot more work since YGOPro class simulators were envisioned as a Windows portable, which is convenient to move around but clashes with the expectations of other platforms. This _may_ work for freedesktop-compliant Linux distributions but a deeper investigation and refactor is needed to make these changes meaningful across all platforms instead of adding more and more platform-specific code.

**Comment by LordYuuma** [comment]
The `YGOPRO_*_PATH` stuff should work on Windows, but we'd need to have ';' as a path separator there.  Also Windows does seem to not like the existence of getenv, but is still forced to provide it.

The XDG stuff is Linux-specific, sure, and I have so far only patched what I found, meaning there could very well be stuff that I missed.  However, it is not as platform-specific as having `std::wstring` everywhere because Windows.  The per-platform overhead consists of correctly setting up `cache_directory`, `config_directory` and `data_directory` according to system expectations and `sysconfig_directory` and `sysdata_directory` according to install paths.  The last one is a bit tricky, as premake does not seem to support install yet.  However, patching the file in-place and then using whatever other build setup should not be too difficult for a script to do.
The detection of absolute paths should perhaps also be handled in `ygo::Utils`, making it two "per-platform" things.  All of the FS stuff would also be considerably easier with C++-17, but we don't have that yet.

**Comment by LordYuuma** [comment]
Since Travis produces meaningful results for once, I've tried resolving some errors.  I was able to find a couple of faults, that arose from me disregarding Windows, but I'm still left with a peculiar nlohmann json error.  I don't recall touching any JSON related code beyond the selection of input files, so I'm not sure where that comes from.  Things appear to be fine on master as well.  Could you look into that?

**Comment by kevinlul** [comment]
If I recall correct, the short version of that is that you have to include `<nlohmann/json.h>` before anything to do with Irrlicht, because the Irrlicht headers contain a few too many macros. It's really, really nasty.

**Comment by LordYuuma** [comment]
Thanks for the hint.  Getting this single line to compile was seriously more effort than it's worth, as I've come to expect from "Win"dows.

Putting this aside for a moment, once it does compile, enabling the XDG_ENVIRONMENT option on Windows should come with reasonable defaults.  Instead of reinventing the wheel, I actually just reimplemented it – the values that I've taken are inspired from GLib,which use the same CSIDL constants for finding the user config, data and cache directories.  As for whether or not it actually works or my helper blows up... I'm clearly not the Windows expert here, you'll have to try that.

I've so far put Apple aside, but as a UNIX system, it should work quite similar to Linux, also w.r.t. XDG.  Specifically putting stuff somewhere in $HOME sounds very reasonable.

As far as maintenance is concerned, instead of using `working_directory`, one will now have to use `data_directory` to store data and `config_directory` to store configuration.  If a global default is to be ensured, one can fall back to the `sys` variant.  `cache_directory` is for temporary data, that can safely be deleted and re-fetched, e.g. the downloaded images.

As noted, I may not yet have patched away all references to the working directory – in fact, I recently discovered one, that would need another variable – but it is already enough to meaningfully play the game.

**Pull request closed without merging**
